"""
Data models and schemas for Module 4: AI Lesson Planner.
"""

from __future__ import annotations
from enum import Enum
from typing import Dict, List, Optional, Any
import uuid
from datetime import datetime, timezone
from pydantic import BaseModel, Field

from app.harness.session import TeachingStrategy, DifficultyLevel
from app.input.models import TeachingRequest, LearnerLevel, TimeBudget, TeachingStyle
from app.rag.models import EvidencePackage
from app.learner.models import LearnerCognitiveState


class LearningObjectiveType(str, Enum):
    UNDERSTAND = "UNDERSTAND"
    EXAM_PREPARATION = "EXAM_PREPARATION"
    PRACTICE = "PRACTICE"
    REVISION = "REVISION"
    APPLICATION = "APPLICATION"
    MASTER_CONCEPT = "MASTER_CONCEPT"


class VisualPlan(BaseModel):
    """Visual design specification generated by the planner and rendered by Module 8."""
    visual_type: str  # circuit_diagram, analogy_water_circuit, plot_curve, code_block, mermaid_diagram
    purpose: str
    concept: str
    timing_seconds: float = 0.0
    required_elements: List[str] = Field(default_factory=list)
    fallback: str = "text_summary"


class LessonSegment(BaseModel):
    """A discrete pedagogical teaching segment within a lesson plan."""
    segment_id: str = Field(default_factory=lambda: f"seg_{uuid.uuid4().hex[:8]}")
    concept: str
    purpose: str  # intro, core_concept, example, visual_analogy, checkpoint_question, remediation, summary
    duration_minutes: float
    teaching_strategy: TeachingStrategy
    explanation_goal: str
    evidence_refs: List[str] = Field(default_factory=list)  # chunk_ids from RAG
    visual_strategy: Optional[VisualPlan] = None
    question_prompt: Optional[str] = None
    question_type: Optional[str] = None  # conceptual, mcq, numerical, application
    expected_learning_outcome: str = "Master targeted concept"
    difficulty: int = 2
    prerequisite_concepts: List[str] = Field(default_factory=list)
    knowledge_confidence: str = "HIGH"  # HIGH, MEDIUM, LOW


class CompletionCriteria(BaseModel):
    minimum_mastery: float = 0.70
    max_unresolved_misconceptions: int = 0
    required_questions_passed: int = 1


class LessonPlan(BaseModel):
    """
    Structured, time-bounded, and level-adapted lesson plan produced by Module 4.
    Consumed directly by Module 5 (Teaching Harness).
    """
    lesson_id: str = Field(default_factory=lambda: f"lesson_{uuid.uuid4().hex[:10]}")
    title: str
    subject: str
    objective: LearningObjectiveType = LearningObjectiveType.UNDERSTAND
    estimated_duration_minutes: int
    concepts: List[str] = Field(default_factory=list)
    segments: List[LessonSegment] = Field(default_factory=list)
    assessment_points: List[str] = Field(default_factory=list)  # segment_ids that pose questions
    visual_plan: List[VisualPlan] = Field(default_factory=list)
    language: str = "en"
    educational_level: LearnerLevel = LearnerLevel.BEGINNER
    difficulty: int = 2
    completion_criteria: CompletionCriteria = Field(default_factory=CompletionCriteria)
    is_grounded: bool = True
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class LessonPlannerInput(BaseModel):
    """Input contract consumed by the Lesson Planner Engine."""
    teaching_request: TeachingRequest
    learner_state: Optional[LearnerCognitiveState] = None
    evidence_package: Optional[EvidencePackage] = None
    available_time: TimeBudget = TimeBudget.TWENTY_MIN
    time_minutes: int = 20
    learning_objective: LearningObjectiveType = LearningObjectiveType.UNDERSTAND
    educational_level: LearnerLevel = LearnerLevel.BEGINNER
    teaching_style: TeachingStyle = TeachingStyle.SIMPLE
    language: str = "en"
    subject: str = "physics"
