"""
Data models and contracts for Module 2: Document Processing & Educational RAG.
"""

from __future__ import annotations
from enum import Enum
from typing import Dict, List, Optional, Any
import uuid
from datetime import datetime, timezone
from pydantic import BaseModel, Field


class ChunkType(str, Enum):
    CONCEPT_DEFINITION = "concept_definition"
    FORMULA_DERIVATION = "formula_derivation"
    WORKED_EXAMPLE = "worked_example"
    EXPLANATION = "explanation"
    CODE_SNIPPET = "code_snippet"
    TABLE_DATA = "table_data"
    SUMMARY = "summary"
    GENERAL = "general"


class GroundingLevel(str, Enum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"


class FormulaNode(BaseModel):
    name: str
    expression: str
    variables: Dict[str, str] = Field(default_factory=dict)
    units: Optional[str] = None


class ExampleNode(BaseModel):
    title: str
    problem_statement: str
    solution_steps: List[str] = Field(default_factory=list)
    final_answer: Optional[str] = None


class DefinitionNode(BaseModel):
    term: str
    definition_text: str
    keywords: List[str] = Field(default_factory=list)


class ConceptNode(BaseModel):
    concept_id: str = Field(default_factory=lambda: f"c_{uuid.uuid4().hex[:8]}")
    name: str
    summary: str
    definitions: List[DefinitionNode] = Field(default_factory=list)
    formulas: List[FormulaNode] = Field(default_factory=list)
    examples: List[ExampleNode] = Field(default_factory=list)
    key_terms: List[str] = Field(default_factory=list)


class SectionNode(BaseModel):
    section_id: str = Field(default_factory=lambda: f"sec_{uuid.uuid4().hex[:8]}")
    title: str
    page_number: int = 1
    content: str
    concepts: List[ConceptNode] = Field(default_factory=list)


class ChapterNode(BaseModel):
    chapter_id: str = Field(default_factory=lambda: f"ch_{uuid.uuid4().hex[:8]}")
    number: Optional[str] = None
    title: str
    sections: List[SectionNode] = Field(default_factory=list)


class DocumentStructure(BaseModel):
    document_id: str
    title: str
    subject: str
    total_pages: int = 1
    language: str = "en"
    chapters: List[ChapterNode] = Field(default_factory=list)
    extracted_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class DocumentChunk(BaseModel):
    """Semantic unit stored in the vector database and retrieved by the RAG engine."""
    chunk_id: str = Field(default_factory=lambda: f"chk_{uuid.uuid4().hex[:12]}")
    document_id: str
    chapter_id: Optional[str] = None
    chapter_title: Optional[str] = None
    section_id: Optional[str] = None
    section_title: Optional[str] = None
    concept_id: Optional[str] = None
    concept_name: Optional[str] = None
    page_number: int = 1
    chunk_index: int = 0
    content: str
    content_type: ChunkType = ChunkType.EXPLANATION
    language: str = "en"
    embedding: Optional[List[float]] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class EvidenceItem(BaseModel):
    chunk_id: str
    document_id: str
    chapter: Optional[str] = None
    section: Optional[str] = None
    page: int = 1
    content_type: ChunkType = ChunkType.EXPLANATION
    excerpt: str
    relevance_score: float = 1.0
    confidence: float = 0.95


class EvidencePackage(BaseModel):
    """
    Evidence package generated by RAG and consumed by Module 4 (Planner) and Module 5 (Harness).
    """
    query: str
    target_concept: str
    grounding_level: GroundingLevel = GroundingLevel.SUPPORTED
    evidence_items: List[EvidenceItem] = Field(default_factory=list)
    combined_context: str
    source_documents: List[str] = Field(default_factory=list)
    confidence: float = 0.95
    limitations_or_gaps: Optional[str] = None
    retrieved_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
